# Generated by Django 6.1.1 on 2026-09-12 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('frontend', 'Front-end Development'), ('backend', 'Back-end Development'), ('devops', 'DevOps'), ('database', 'Database Development')], default='frontend', max_length=20)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
