# Generated by Django 6.1 on 2026-09-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_experience_started_at'),
        ('main', '0004_populate_initial_data'),
    ]

    operations = [
    ]
