# Generated by Django 6.1.1 on 2026-09-26 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='endorsed_by',
            field=models.ManyToManyField(blank=True, related_name='endorsed_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
